### ISSUE TITLE
Introduce notion of "suspiciously long-running command"

### ISSUE THREAD

**Issue by tim-mccurrach** [yunojuno/django-management-command-log#13]
Currently, the life-cycle of `management_command_log.exit_code` starts at `None` and then goes to 0 (succeeded), 1 (failure) or 2 (partial failure/success).

At the moment, if a command is still running, it's `exit_code` will not have been set yet, and so it will still be `None`. In django-admin list-view, the `exit_code` column shows a cross or a tick based on the following line:
```
return obj.exit_code == ManagementCommandLog.EXIT_CODE_SUCCESS
```

A cross symbol for a command that is still running is misleading, so we should correct this. 

In principle this is easy to do. What makes the problem more complicated is that when the process that is running the command is stopped or crashes before the command has finished running, the `exit_code` remains as `None`. This should be recorded as a failure, but currently isn't.

(This problem means that when you filter for failures, you only see commands that are recorded as failures, rather than those that also failed and weren't recorded as a failure).

As such within the django-admin there are 2 problems:
1) Jobs that are still running are displayed as failing (a red cross at least)
2) Some jobs that have failed, are never recorded as failed, and so don't show up when you filter for failures. (They are indistinguishable from jobs that are still running)

Python does provide a few hooks for handling processes that quit, however I think going down this route is probably not the best way. There are lots of ways the process could finish early, it could run out of memory, it could be killed by a parent process, it could just stop (as in the case of a power-failure). Managing all of these will be difficult to do correctly, and adding a database call whilst everything is shutting down may be a bad idea anyway.

I propose we don't actually change anything fundamental about `exit_code`. But in the django-admin interface we could flag jobs that have no `exit_code` and that have a start-time beyond a certain threshold. This threshold could be a global setting, or be defined as a class attribute on a per-command basis.

This would allow us to make an attempt at distinguishing between jobs that are currently running, and jobs that have stopped early.

**Comment by hugorodgerbrown** [comment]
How about immediately setting exit_code to 2 (partial) - technically once it's started it's either going to complete and thereby move to 0 / 1, or get left unchanged(the scenario under discussion). I'd argue that a command that is both partial failure and partial success until it completes one way or another - it's Schrödinger's command. If you set it to 2 initially and just leave it at that then you can also identify it - "partial success with no end timestamp" means exactly that - it started, but never completed, and you're going to have to take a look inside the box to see what happened.

**Comment by tim-mccurrach** [comment]
> How about immediately setting exit_code to 2 (partial) 

Semantically this might make more sense, but it doesn't change the underlying problem that we can't differentiate between currently running commands and commands that ended unexpectedly. In fact, it makes the problem a little bit worse. With the current set-up, we know that:
 - `None` means on-going or ended badly
 - `exit_code==2` means the command has finished running and has partially failed, but in a way that has been accounted for by the user, and so changes have not been rolled back.
 
 If we set `exit_code` to 2 from the outset, we are just further reducing the "resolution", since we conflate 3 scenarios into a single state. It would also be a breaking change.
 
 
The problem behind the problem is that in the django-admin I want to be able to see a single list of all of the commands that have failed, so that I can deal with them. 
 
At the moment I can't do that because commands that fail badly aren't shown in the list if I click on the "failed" filter. Including `exit_code==None` would put currently running commands into that view, which might be confusing. The notion of a cut-off time after which we include logs with `exit_code==None` in such a list would mitigate this.

An alternative approach could be an additional filter, that showed everything that wasn't `exit_code==1`. The list could show the exit_code and start-time and so we would be able to clearly differentiate between true failures and Schrodinger commands that need further investigation. Does this seem like a reasonable solution?

**Comment by hugorodgerbrown** [comment]
How about using `-1` as the "in progress" code?

**Comment by hugorodgerbrown** [comment]
Alternatively we just add a new admin filter?
